DOC: Update installation instructions
demianw/tract_querier pull request #73
Opened 2024-12-10 22:05 UTC by jhlegarreta

Update installation instructions:
- Update the dependencies versions.
- `Canopy` is no longer maintained/available, so remove it.
- Update the instal command to use `pip` as the build system has been changed and there is no `setup.py` file.

2024-12-10 22:05 UTC, jhlegarreta commented
Draft until tag/release.

2024-12-11 16:26 UTC, demianw requested changes

2024-12-11 16:26 UTC, demianw commented on doc/installation_instructions.rst
> +  pip install
this should be `pip install .`

2024-12-11 16:59 UTC, jhlegarreta commented on doc/installation_instructions.rst
> +  pip install
Thanks for checking. Fixed in f991c57.

2024-12-16 09:01 UTC, merged

2025-06-03 18:35 UTC, tashrifbillah commented
@demianw , I was going to submit a PR but I see that somebody addressed this before. Did you ever deploy this merge? I am asking because the installation instruction is still outdated:

2025-06-03 18:36 UTC, tashrifbillah commented
@demianw , I was going to submit a PR but I see that somebody addressed this before. Did you ever deploy this merge? I am asking because the installation instruction is still outdated:
http://demianw.github.io/tract_querier/installation_instructions.html#installation